-- roles
CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- users
CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(100) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    email      VARCHAR(150) UNIQUE,
    enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- user_roles
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- unidades (apartments)
CREATE TABLE unidades (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bloco         VARCHAR(50)  NOT NULL,
    numero        VARCHAR(20)  NOT NULL,
    andar         VARCHAR(20),
    vaga          VARCHAR(20),
    situacao      VARCHAR(20)  NOT NULL DEFAULT 'OCUPADA',
    identificacao VARCHAR(100) NOT NULL,
    UNIQUE (bloco, numero)
);

-- moradores
CREATE TABLE moradores (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidade_id          BIGINT       NOT NULL REFERENCES unidades(id),
    nome                VARCHAR(200) NOT NULL,
    cpf                 VARCHAR(14)  NOT NULL UNIQUE,
    telefone            VARCHAR(30),
    email               VARCHAR(150),
    tipo_morador        VARCHAR(30)  NOT NULL DEFAULT 'PROPRIETARIO',
    responsavel_unidade VARCHAR(3)   NOT NULL DEFAULT 'NAO'
);

-- ocorrencias
CREATE TABLE ocorrencias (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidade_id           BIGINT REFERENCES unidades(id),
    aberto_por_id        BIGINT REFERENCES moradores(id),
    tipo                 VARCHAR(30)  NOT NULL DEFAULT 'MANUTENCAO',
    prioridade           VARCHAR(10)  NOT NULL DEFAULT 'MEDIA',
    status               VARCHAR(20)  NOT NULL DEFAULT 'ABERTA',
    titulo               VARCHAR(255) NOT NULL,
    descricao            TEXT         NOT NULL,
    data_hora_abertura   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_hora_fechamento TIMESTAMP
);

-- reservas
CREATE TABLE reservas (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidade_id     BIGINT      NOT NULL REFERENCES unidades(id),
    solicitante_id BIGINT      NOT NULL REFERENCES moradores(id),
    area           VARCHAR(30) NOT NULL,
    inicio         TIMESTAMP   NOT NULL,
    fim            TIMESTAMP   NOT NULL,
    status         VARCHAR(20) NOT NULL DEFAULT 'SOLICITADA',
    observacao     TEXT
);

-- visitantes
CREATE TABLE visitantes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidade_id        BIGINT       NOT NULL REFERENCES unidades(id),
    nome              VARCHAR(200) NOT NULL,
    documento         VARCHAR(50),
    telefone          VARCHAR(30),
    tipo_visitante    VARCHAR(30)  NOT NULL DEFAULT 'VISITA',
    autorizado_por_id BIGINT REFERENCES moradores(id),
    ativo             VARCHAR(3)   NOT NULL DEFAULT 'SIM'
);
