-- condominios
CREATE TABLE condominios (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                  VARCHAR(200) NOT NULL,
    cnpj                  VARCHAR(18)  UNIQUE,
    logradouro            VARCHAR(255),
    numero                VARCHAR(20),
    complemento           VARCHAR(100),
    bairro                VARCHAR(100),
    cidade                VARCHAR(100),
    uf                    VARCHAR(2),
    cep                   VARCHAR(10),
    telefone              VARCHAR(30),
    email                 VARCHAR(150),
    nome_administrador    VARCHAR(200),
    telefone_administrador VARCHAR(30)
);

-- blocos
CREATE TABLE blocos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condominio_id   BIGINT      NOT NULL REFERENCES condominios(id) ON DELETE CASCADE,
    nome            VARCHAR(50) NOT NULL,
    descricao       VARCHAR(255),
    total_andares   INTEGER     NOT NULL DEFAULT 1,
    total_unidades  INTEGER     NOT NULL DEFAULT 0,
    UNIQUE (condominio_id, nome)
);

-- colaboradores
CREATE TABLE colaboradores (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR(200) NOT NULL,
    cpf                VARCHAR(14)  NOT NULL UNIQUE,
    rg                 VARCHAR(30),
    cargo              VARCHAR(30)  NOT NULL,
    telefone           VARCHAR(30),
    email              VARCHAR(150),
    data_admissao      DATE,
    data_desligamento  DATE,
    ativo              BOOLEAN      NOT NULL DEFAULT TRUE,
    turno              VARCHAR(50),
    observacoes        TEXT
);

-- proprietarios
CREATE TABLE proprietarios (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidade_id           BIGINT       NOT NULL REFERENCES unidades(id),
    nome                 VARCHAR(200) NOT NULL,
    cpf                  VARCHAR(14)  NOT NULL UNIQUE,
    rg                   VARCHAR(30),
    telefone             VARCHAR(30),
    email                VARCHAR(150),
    profissao            VARCHAR(100),
    endereco_principal   VARCHAR(255),
    reside_no_condominio BOOLEAN      NOT NULL DEFAULT FALSE
);
