-- taxas condominiais
CREATE TABLE taxas_condominiais (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidade_id       BIGINT        NOT NULL REFERENCES unidades(id),
    valor            DECIMAL(10,2) NOT NULL,
    competencia_ano  INTEGER       NOT NULL,
    competencia_mes  INTEGER       NOT NULL,
    vencimento       DATE          NOT NULL,
    data_pagamento   DATE,
    multa            DECIMAL(10,2),
    juros            DECIMAL(10,2),
    status           VARCHAR(20)   NOT NULL DEFAULT 'PENDENTE',
    observacao       TEXT,
    criado_em        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (unidade_id, competencia_ano, competencia_mes)
);

-- receitas e despesas
CREATE TABLE receitas_despesas (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo         VARCHAR(10)   NOT NULL,
    categoria    VARCHAR(30)   NOT NULL,
    descricao    VARCHAR(255)  NOT NULL,
    valor        DECIMAL(10,2) NOT NULL,
    data         DATE          NOT NULL,
    fornecedor   VARCHAR(200),
    numero_nota  VARCHAR(50),
    observacao   TEXT,
    criado_em    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
