-- avisos (quadro de avisos)
CREATE TABLE avisos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo       VARCHAR(255) NOT NULL,
    conteudo     TEXT         NOT NULL,
    tipo         VARCHAR(20)  NOT NULL DEFAULT 'INFORMATIVO',
    autor_id     BIGINT       REFERENCES users(id),
    publicado_em TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expiracao_em DATE,
    ativo        BOOLEAN      NOT NULL DEFAULT TRUE
);

-- documentos
CREATE TABLE documentos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(255) NOT NULL,
    descricao       VARCHAR(500),
    categoria       VARCHAR(100) NOT NULL,
    nome_arquivo    VARCHAR(255) NOT NULL,
    tipo_conteudo   VARCHAR(100) NOT NULL,
    tamanho_bytes   BIGINT       NOT NULL,
    caminho_arquivo VARCHAR(500) NOT NULL,
    enviado_por_id  BIGINT       REFERENCES users(id),
    enviado_em      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ativo           BOOLEAN      NOT NULL DEFAULT TRUE
);
