CREATE TABLE comunicados (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo       VARCHAR(255) NOT NULL,
    corpo        TEXT         NOT NULL,
    tipo         VARCHAR(30)  NOT NULL DEFAULT 'COMUNICADO',
    autor        VARCHAR(200) NOT NULL,
    publicado_em TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ativo        BOOLEAN      NOT NULL DEFAULT TRUE
);
